### ISSUE TITLE
Better Infrastructure validation for `select` attribute

### ISSUE THREAD

**Issue by sanderblue** [terraform-providers/terraform-provider-newrelic#606]
Related : #589 

### Objective
It looks like we might need some client-side validation for the `select` attribute. 

More specifically, using a combination of `type = "infra_metric"`  with `select = "memoryUsedPercent"` does not work. 

Instead, it looks using `memoryFreeBytes/memoryTotalBytes*100` does work.

e.g.
```hcl
# ...
type       = "infra_metric"
select     = "memoryFreeBytes/memoryTotalBytes*100"
# ...
```

### Acceptance Criteria
- Some level of client-side validation is set up. 
    > <small>(or implement some other mechanism to help the user out, although I didn't seem to get errors back from the API for this scenario)</small>
- Where applicable, update the Infra Alert Condition documentation to hopefully provide better explanations/examples of the allowed combinations of values for the different types of metrics.

**Comment by Benno007** [comment]
Sorry to bring up an old issue, but this would be great. I just spent quite a while trying to setup an alert for `provider.swapUsageBytes.Average`, which is the value in the dropdown in the infrastructure menu. I was just about to drop using newrelic provider altogether. Just using `provider.swapUsageBytes.Average` was enough to completely crash Terraform (0.14.11, newrelic provider 0.22.1)

I was assuming the available values would match what is in the dropdown? Is this not the case?

<img width="999" alt="Screen Shot 2021-05-17 at 8 56 44 am" src="https://user-images.githubusercontent.com/313195/118415462-d01d0800-b6ed-11eb-81f7-d47649d2b99d.png">



```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
```

```
2021-05-17T08:35:35.320+1000 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-05-17T08:35:35.322+1000 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/newrelic/newrelic/2.22.1/darwin_amd64/terraform-provider-newrelic_v2.22.1 pid=2613
2021-05-17T08:35:35.322+1000 [DEBUG] plugin: plugin exited
```


```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.22.1"
    }
  }
}
# API key provided by env var
provider "newrelic" {
  account_id = "xxx"
  region     = "US"
}
resource "newrelic_infra_alert_condition" "high_swap_usage" {
  policy_id = data.newrelic_alert_policy.alert_policy.id

  name                 = "Swap ${module.names.name}-${var.aws_region}"
  description          = "Warning for when RDS Swap Usage goes above 80% for ${module.names.name}"
  type                 = "infra_metric"
  event                = "DatastoreSample"
  select               = "provider.swapUsageBytes.Average"
  comparison           = "above"
  where                = "(entityName LIKE '%${module.names.name}%' AND awsRegion = '${var.aws_region}')"
  integration_provider = "RdsDbInstance"

  warning {
    duration      = 5
    value         = 120000000
    time_function = "all"
  }
  provider = newrelic
}

```

**Comment by jthurman42** [comment]
I can replicate this with a slightly modified version of the above example (remove vars/add a policy)

```
[INFO]  Starting apply for newrelic_infra_alert_condition.high_swap_usage
[DEBUG] newrelic_infra_alert_condition.high_swap_usage: applying the planned Create change
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: PANIC: runtime error: index out of range [0] with length 0
[DEBUG] provider.terraform-provider-newrelic_v2.22.1:
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: goroutine 56 [running]:
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandInfraAlertThreshold(0x1b9a9c0, 0xc00000c750, 0x8)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_infra_alert_condition.go:59 +0x2a6
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandInfraAlertCondition(0xc0003b4000, 0x0, 0xc00008e2c0, 0x1d71006)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_infra_alert_condition.go:20 +0x2fd
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicInfraAlertConditionCreate(0xc0003b4000, 0x1bece00, 0xc000839aa0, 0x2, 0x25e1e40)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_infra_alert_condition.go:181 +0x6e
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000922b40, 0xc000620500, 0xc000586380, 0x1bece00, 0xc000839aa0, 0x1bff901, 0xc00069a0d8, 0xc00064a330)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x375
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000118900, 0xc0007e1a38, 0xc000620500, 0xc000586380, 0xc00063ba68, 0xc000612500, 0x1c01a20)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x99
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000114920, 0x1f6fbf0, 0xc0006f8030, 0xc00060c000, 0xc000114920, 0xc0006f8030, 0xc0005edba0)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x8a5
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1d18360, 0xc000114920, 0x1f6fbf0, 0xc0006f8030, 0xc0006fa000, 0x0, 0x1f6fbf0, 0xc0006f8030, 0xc0006f4800, 0x3d5)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a21c0, 0x1f79d38, 0xc0001a8a80, 0xc0002feb00, 0xc00008d440, 0x25a0b80, 0x0, 0x0, 0x0)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: google.golang.org/grpc.(*Server).handleStream(0xc0000a21c0, 0x1f79d38, 0xc0001a8a80, 0xc0002feb00, 0x0)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000110200, 0xc0000a21c0, 0x1f79d38, 0xc0001a8a80, 0xc0002feb00)
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
[DEBUG] provider.terraform-provider-newrelic_v2.22.1: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

Looks like we assume we're getting data back [here](https://github.com/newrelic/terraform-provider-newrelic/blob/master/newrelic/structures_newrelic_infra_alert_condition.go#L59), and in this case we are not, so `index out of range` panic vs returning an error.

**Comment by jthurman42** [comment]
@Benno007 thanks for reporting the bug, which is actually unrelated to the 'select' config.  The issue is that you did not define a 'Critical' threshold which is required, and exposed a bug where if `critical` is not set, the provider panics.

Change you `warning` to `critical` as follows, and it works.  If you want a warning level, add a critical that is greater than the warning:

```
  critical {
    duration      = 5
    value         = 120000000
    time_function = "all"
  }
```

**Comment by kidk** [comment]
Closing this as only NRQL alerts will be supported long term and no development is happening on infrastructure alerts.
